// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKKvZjHH7t9SZGMhyownWsFXrh8TX43qM',
    appId: '1:787090672699:web:2df94aca295d84c656a01e',
    messagingSenderId: '787090672699',
    projectId: 'warisannusantara-8c40e',
    authDomain: 'warisannusantara-8c40e.firebaseapp.com',
    storageBucket: 'warisannusantara-8c40e.firebasestorage.app',
    measurementId: 'G-861CJJF5CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRBfEj8RR0oTHfYctCOjKT8vqB-WaX4g',
    appId: '1:787090672699:android:b07f3d368bb9e2da56a01e',
    messagingSenderId: '787090672699',
    projectId: 'warisannusantara-8c40e',
    storageBucket: 'warisannusantara-8c40e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzAEP0k1wcCblH_oY8u-YgX3WbV7MNJU',
    appId: '1:787090672699:ios:b96ea189e4f9c9f256a01e',
    messagingSenderId: '787090672699',
    projectId: 'warisannusantara-8c40e',
    storageBucket: 'warisannusantara-8c40e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXzAEP0k1wcCblH_oY8u-YgX3WbV7MNJU',
    appId: '1:787090672699:ios:b96ea189e4f9c9f256a01e',
    messagingSenderId: '787090672699',
    projectId: 'warisannusantara-8c40e',
    storageBucket: 'warisannusantara-8c40e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKKvZjHH7t9SZGMhyownWsFXrh8TX43qM',
    appId: '1:787090672699:web:852c83ad0f23280656a01e',
    messagingSenderId: '787090672699',
    projectId: 'warisannusantara-8c40e',
    authDomain: 'warisannusantara-8c40e.firebaseapp.com',
    storageBucket: 'warisannusantara-8c40e.firebasestorage.app',
    measurementId: 'G-YVLL5R10WG',
  );
}
